-- Migration 012: one-off assignment of Segments to existing prospects.
-- Best-effort mapping based on each organisation's name and original
-- Category text. Left unset where nothing in the curated Segments list
-- is a reasonable fit (expected -- the list is deliberately narrow).
-- Please review and adjust individual assignments as needed.
-- Run this in the Supabase SQL Editor AFTER migration 011_segments.sql.

update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = '42nd Street' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Access Sport' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'ACET Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'Action Tutoring' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'ACTIVATE Leadership' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'ACTIVATE! Change Drivers' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Active Essex Foundation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Disabilities') where name = 'AFK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'akt' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Befriending') where name = 'b:friend' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Baytree Centre' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Befriending') where name = 'Befriending Networks' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Big Brothers Big Sisters South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Birmingham City Mission' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'Black Country Foodbank' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Brentford FC Community Sports Trust' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Long-term unemployment') where name = 'Brotherhood of St Laurence' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Cape Mental Health' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Livelihoods') where name = 'CareerSeekers' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Befriending') where name = 'Carers Leeds' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Caritas Diocese of Salford' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth justice') where name = 'Catch22' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Incubators & Accelerators') where name = 'CDRA — Community Development Resources Association' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Chance to Shine' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'Christel House South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Christian') where name = 'Christians Against Poverty' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Church Urban Fund' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'City Gateway' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'City Year UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth justice') where name = 'ConnectFutures' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Coram Leap Confronting Conflict' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Cotlands' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Depaul UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social Housing community projects') where name = 'Development Action Group (DAG)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Dorset Mind' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'East Lothian Foodbank (Scotland)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Education Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'ELRU – Early Learning Resource Unit' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Livelihoods') where name = 'EmpowaYouth' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'Equal Education' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'EveryYouth' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Extern' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'FAMSA (Families South Africa)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'FEAST With Us' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Long-term unemployment') where name = 'Fitted for Work' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'Food Bank Aid' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'FoodCycle' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'FoodForward SA' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Football Beyond Borders' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Collective Impact') where name = 'Foyer Federation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Fresh Futures' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Future Africa International' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'Future First' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Future Frontiers' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Generation Kenya' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Generation South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Generation UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Girl Effect South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'GirlCode' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Good Work Foundation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'GoodWork' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Grassroot Soccer SA' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Grassroot Soccer South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Greenhouse Sports' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Grootbos Foundation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Collective Impact') where name = 'Groundwork UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Grow Great' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Hertfordshire Mind Network' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'HOPE Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Hope Cape Town' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Community Climate Action') where name = 'Hope for the Future' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Hope Worldwide South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Ikamva Labantu' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Ilifa Labantwana' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'IntoUniversity' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Incubators & Accelerators') where name = 'Inyathelo' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Isle of Wight Youth Trust' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Jigsaw' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Criminal justice') where name = 'Key4Life' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Khulisa (UK)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Kick London' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Kids First Australia (incorp. Whitelion)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'LEAP Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Leap Confronting Conflict' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'LEAP Science and Maths Schools' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Leeds Mind' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'Leeds North & West Foodbank' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'Literacy Pirates' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'London Youth' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Making The Leap' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Mamelani Projects' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Manchester Mind' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Children with disabilities') where name = 'Mason Foundation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Maudsley Charity' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'MCR Pathways' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Mentoring Plus Bath' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'MIET Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Mind in Salford' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'Money Ready (formerly MyBNK)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Mpilonhle' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Grant making') where name = 'NACOSA' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'NACSA' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'National Business Initiative (NBI)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Incubators & Accelerators') where name = 'National Mentorship Movement' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'New Horizon Youth Centre' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Criminal justice') where name = 'NICRO' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'Nourish Community Foodbank' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Oasis Charitable Trust' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Oasis Community Trust' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'One to One Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'Operation Hunger' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Palace For Life Foundation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'PAPYRUS UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Pathways to Education' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Penreach' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Philani' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth justice') where name = 'Power2' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Disabilities') where name = 'Pure Innovations' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Ranyaka Community Transformation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Befriending') where name = 'Re-engage' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'ReachOut UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Criminal justice') where name = 'Recycling Lives' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Resurgo (Spear)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Rise Up UK' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'SAEP (South African Education Project)' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'SchoolNet South Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Second Step' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'Sikhula Sonke' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Siyabonga Africa' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Early Years') where name = 'SOS Children''s Villages SA' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'South East London Mind' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Sozo Foundation' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Spitalfields Crypt Trust' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Mental health & wellbeing') where name = 'Sport in Mind' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Sported' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Church-based projects and ministries') where name = 'Spurgeons' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Criminal justice') where name = 'St Giles Trust' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'Step by Step' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'Street League' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Sport-based youth engagement') where name = 'StreetGames' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'International Development') where name = 'Thandulwazi' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Social mobility') where name = 'The Access Project' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Foodbank') where name = 'The Bread and Butter Thing' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Criminal justice') where name = 'The Clink Charity' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Livelihoods') where name = 'The Clothing Bank' and segment_id is null;
update organisations set segment_id = (select id from segments where name = 'Youth work') where name = 'The Girls'' Network' and segment_id is null;
